// <auto-generated />
using System;
using MaisonCalliard.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MaisonCalliard.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MaisonCalliard.Domain.Entities.AppSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("LeadTimeDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            LeadTimeDays = 3
                        });
                });

            modelBuilder.Entity("MaisonCalliard.Domain.Entities.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CartId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OptionLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("TaxRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("MaisonCalliard.Domain.Entities.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("BakedOnSite")
                        .HasColumnType("boolean");

                    b.Property<bool?>("BakedThisMorning")
                        .HasColumnType("boolean");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<double?>("TaxRate")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("MaisonCalliard.Domain.Entities.NewsItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NewsItems");
                });

            modelBuilder.Entity("MaisonCalliard.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CustomerEmailSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("InternalNotificationSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPrinted")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PickupDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReceiptNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReceiptSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StripePaymentIntentId")
                        .HasColumnType("text");

                    b.Property<string>("StripeSessionId")
                        .HasColumnType("text");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptNumber")
                        .IsUnique()
                        .HasFilter("\"ReceiptNumber\" IS NOT NULL");

                    b.HasIndex("StripePaymentIntentId")
                        .IsUnique()
                        .HasFilter("\"StripePaymentIntentId\" IS NOT NULL");

                    b.HasIndex("StripeSessionId")
                        .IsUnique()
                        .HasFilter("\"StripeSessionId\" IS NOT NULL");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MaisonCalliard.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("BakedOnSite")
                        .HasColumnType("boolean");

                    b.Property<bool?>("BakedThisMorning")
                        .HasColumnType("boolean");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("ImagePosition")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("50% 50%");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSeason")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVegan")
                        .HasColumnType("boolean");

                    b.Property<string>("PriceOptions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Stock")
                        .HasColumnType("text");

                    b.Property<int?>("Style")
                        .HasColumnType("integer");

                    b.Property<double?>("TaxRate")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MaisonCalliard.Domain.Entities.ReceiptSequence", b =>
                {
                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<int>("LastNumber")
                        .HasColumnType("integer");

                    b.HasKey("Year");

                    b.ToTable("ReceiptSequences");
                });

            modelBuilder.Entity("MaisonCalliard.Domain.Entities.CartItem", b =>
                {
                    b.HasOne("MaisonCalliard.Domain.Entities.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MaisonCalliard.Domain.Entities.MenuItem", b =>
                {
                    b.OwnsOne("MaisonCalliard.Domain.ValueObjects.LocalizedText", "Description", b1 =>
                        {
                            b1.Property<Guid>("MenuItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Se")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("MenuItemId");

                            b1.ToTable("MenuItems");

                            b1.WithOwner()
                                .HasForeignKey("MenuItemId");
                        });

                    b.OwnsOne("MaisonCalliard.Domain.ValueObjects.LocalizedText", "Ingredients", b1 =>
                        {
                            b1.Property<Guid>("MenuItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Se")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("MenuItemId");

                            b1.ToTable("MenuItems");

                            b1.WithOwner()
                                .HasForeignKey("MenuItemId");
                        });

                    b.OwnsOne("MaisonCalliard.Domain.ValueObjects.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<Guid>("MenuItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Se")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("MenuItemId");

                            b1.ToTable("MenuItems");

                            b1.WithOwner()
                                .HasForeignKey("MenuItemId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Ingredients")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("MaisonCalliard.Domain.Entities.NewsItem", b =>
                {
                    b.OwnsOne("MaisonCalliard.Domain.ValueObjects.LocalizedText", "Subtitle", b1 =>
                        {
                            b1.Property<Guid>("NewsItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Se")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("NewsItemId");

                            b1.ToTable("NewsItems");

                            b1.WithOwner()
                                .HasForeignKey("NewsItemId");
                        });

                    b.OwnsOne("MaisonCalliard.Domain.ValueObjects.LocalizedText", "Title", b1 =>
                        {
                            b1.Property<Guid>("NewsItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Se")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("NewsItemId");

                            b1.ToTable("NewsItems");

                            b1.WithOwner()
                                .HasForeignKey("NewsItemId");
                        });

                    b.Navigation("Subtitle")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("MaisonCalliard.Domain.Entities.Product", b =>
                {
                    b.OwnsOne("MaisonCalliard.Domain.ValueObjects.LocalizedText", "Description", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Se")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("MaisonCalliard.Domain.ValueObjects.LocalizedText", "Ingredients", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Se")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("MaisonCalliard.Domain.ValueObjects.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Se")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Ingredients")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("MaisonCalliard.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
